config/blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, CategoryListView #,api

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="home"),
    path('page/<int:page>', ArticleListView.as_view(), name="home"),
    # path('api', api, name="api")
    path('article/<slug:slug>', ArticleDetailView.as_view(), name="detail"),
    path('category/<slug:slug>', CategoryListView.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryListView.as_view(), name="category")
]   

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from extentions.utils import jalali_converter

# My Managers:
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Create your models here.
class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name = 'عنوان دسته بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name = 'شناسه دسته بندی')
    status = models.BooleanField(default=True, verbose_name = 'نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ("d", "پیش نویس"),
        ("p", "منتشر شده"),
    )

    title = models.CharField(max_length=200, verbose_name = 'عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name = 'شناسه مقاله')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name = 'محتوا')
    thumbnail = models.ImageField(upload_to="image", verbose_name = 'تصویر موجود')
    publish = models.DateTimeField(default=timezone.now, verbose_name = 'زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name = 'وضعیت')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html("<img width=90 height=80 style='object-fit: cover; border-radius: 4px' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = "تصویر"

    objects = ArticleManager()

config/blog/views.py
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse, JsonResponse
from .models import Article, Category

# Create your views here.
# def home(request, page=1):
#     articles_list = Article.objects.published()
#     paginator = Paginator(articles_list, 4)
#     articles = paginator.get_page(page)

#     context = {
#         # "articles": Article.objects.all()
#         # "articles": Article.objects.published(),
#         "articles": articles,
#     }
#     return render(request, "blog/home.html", context)
class ArticleListView(ListView):
    # model = Article
    queryset = Article.objects.published()
    paginate_by = 4
    # template_name = "blog/home.html"


# def detail(request, slug):
#     context = {
#         # "articles": Article.objects.all()
#         "article": get_object_or_404(Article.objects.published(), slug=slug)
#     }
#     return render(request, "blog/detail.html", context)
class ArticleDetailView(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list = category.articles.published()
#     paginator = Paginator(articles_list, 2)
#     articles = paginator.get_page(page)

#     context = {
#         "category": category,
#         "articles": articles,
#     }
#     return render(request, "blog/category.html", context)
class CategoryListView(ListView):
    paginate_by = 4
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

'''
def home(request):
    context = {
        "articles": [
            {
                "title": "دستاورد بزرگ مریخ نورد استقامت: تولید اکسیژن روی سطح سیاره سرخ",
                "description": "فرمول نتفلیکس برای گسترده کردن سلطتنش ساده است: هر ایده‌ای را قبول کن و کارگردان هرچقدر پول لازم داشت، به او بده. این قضیه برای ...",
                "img": "https://digiato.com/wp-content/uploads/2022/09/yaze6df9AMIA9oeDEbIZ4zOTRCJ-330x200.webp"
            },
            {
                "title": "گوش کنید: ناسا صدای دیجیتالی تصاویر خیره کننده جیمز وب را منتشر کرد",
                "description": "ناسا داده‌های اولین تصاویر تمام رنگی تلسکوپ جیمز وب را به موسیقی تبدیل کرده است.",
                "img": "https://digiato.com/wp-content/uploads/2022/09/Screenshot-504-330x200.png"
            }
        ]
    }
    return render(request, "blog/home.html", context)
'''


# def api(request):
#     data = {
#         "1": {
#             "title": "سلام عرفان",
#             "id": 1
#             },
#         "2": {
#             "title": "سلام مقاله",
#             "id": 2
#             },
#         "3": {
#             "title": "سلام بر همه",
#             "id": 3
#             },
#         "4": {
#             "title": "سلام سلام",
#             "id": 4
#             }
#     }

#     return JsonResponse(data)

config/blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

config/blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block title %} {{object.title}} {% endblock %}

{% block main %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{{object.thumbnail.url}}'); height: 100vh;">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>{{object.title}}</h1>
                        <p>{{ object.jpublish }}</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7" style="text-align: justify;">
                    <p>{{object.description|linebreaks}}</p>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

config/blog/templates/blog/article_list.html
{% extends 'blog/base.html' %} 
{% load static %}
{% block title %} صفحه اصلی {% endblock %}
{% block main %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>وبلاگ عرفان</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for article in object_list %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{article.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{article.description|truncatewords:20}}
                    </h3>
                    </a>
                    <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">عرفان</a>
                    {{article.jpublish}}
                    </p>
                </div>
                <div>
                    {% for cat in article.category_published.all %}
                        <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

        <!-- Pager-->
                {% if is_paginated %}
                    <div class="d-flex justify-content-end mb-4 gap-2">
                        
                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary text-uppercase" href="{% url 'blog:home' page_obj.previous_page_number %}">پست های جدید &rAarr;</a>
                        {% endif %}
                        
                        {% if page_obj.has_next %}
                        <a class="btn btn-primary text-uppercase" href="{% url 'blog:home' page_obj.next_page_number %}">پست های قدیمی &lAarr;</a>
                        {% endif %}
                    
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

config/blog/templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" /> -->
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5" style="display: flex; align-items: baseline;">
                <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>
        
        <!-- Main Content-->
        {% block main %}

        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

config/blog/templates/blog/category_list.html
{% extends 'blog/base.html' %} 
{% load static %}
{% block title %} صفحه اصلی {% endblock %}
{% block main %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>وبلاگ عرفان</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <h4 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h4>
            {% for article in object_list %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{article.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{article.description|truncatewords:20}}
                    </h3>
                    </a>
                    <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">عرفان</a>
                    {{article.jpublish}}
                    </p>
                </div>
                <div>
                    {% for cat in article.category_published.all %}
                        <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

        <!-- Pager-->
        {% if is_paginated %}
            <div class="d-flex justify-content-end mb-4">
            
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug page_obj.previous_page_number %}">پست های جدید &rAarr;</a>
                {% endif %}
                
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug page_obj.next_page_number %}">پست های قدیمی &lAarr;</a>
                {% endif %}
            
            </div>
        {% endif %}
        </div>
    </div>
    </div>
{% endblock %}

config/blog/templates/blog/partials/category_loop.html
<ul class="navbar-nav ml-auto" id="submenu">
    {% for cat in cat.children.active %}
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
            {% if cat.children.active %}
                {% include 'blog/partials/category_loop.html' %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

config/blog/templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse nav" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">خانه</a></li>
        {% for cat in category %}
            {% if cat.parent == None %}
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                    {% if cat.children.active %}
                        {% include 'blog/partials/category_loop.html' %}
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>